name: breath_easy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  haptic_feedback: ^0.5.1+1
  wakelock_plus: ^1.2.0
  change_app_package_name: ^1.5.0
  provider: ^6.1.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
flutter:
  uses-material-design: true
